# Generated by Django 3.1.7 on 2021-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210302_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='createYear',
            field=models.DateTimeField(null='false', verbose_name='Год выпуска'),
            preserve_default='false',
        ),
    ]
