# Generated by Django 3.1.7 on 2021-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_createyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='createYear',
            field=models.DateField(null='false', verbose_name='Год выпуска'),
        ),
    ]
