# Generated by Django 3.1.7 on 2021-03-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
