# Generated by Django 3.1.7 on 2021-03-04 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210304_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 13, 13, 11, 321568), verbose_name='Дата заявки'),
        ),
    ]
